/**
 * Figure defaults for the AZ-900 Azure Fundamentals lesson. Diagrams are
 * generated by scripts/gen-az900-figures.mjs into /public/figures/az900/ and
 * merged with FIGURE_DEFAULTS at render time (staff uploads still override).
 */
import type { FigureDefault } from "./figureDefaults";

const src = (name: string) => "/figures/az900/" + name;

const own = { author: "ITSS Learn (course materials)", license: "Course material", sourceUrl: "" };

export const AZ900_FIGURES: Record<string, FigureDefault> = {
  "az900-exam-areas": { src: src("az900-exam-areas.svg"), ...own },
  "az900-cloud-services": { src: src("az900-cloud-services.svg"), ...own },
  "az900-shared-responsibility": { src: src("az900-shared-responsibility.svg"), ...own },
  "az900-cloud-models": { src: src("az900-cloud-models.svg"), ...own },
  "az900-pricing-models": { src: src("az900-pricing-models.svg"), ...own },
  "az900-serverless": { src: src("az900-serverless.svg"), ...own },
  "az900-scaling": { src: src("az900-scaling.svg"), ...own },
  "az900-benefits": { src: src("az900-benefits.svg"), ...own },
  "az900-service-types": { src: src("az900-service-types.svg"), ...own },
  "az900-regions-zones": { src: src("az900-regions-zones.svg"), ...own },
  "az900-hierarchy": { src: src("az900-hierarchy.svg"), ...own },
  "az900-compute-services": { src: src("az900-compute-services.svg"), ...own },
  "az900-vm-resources": { src: src("az900-vm-resources.svg"), ...own },
  "az900-vnet": { src: src("az900-vnet.svg"), ...own },
  "az900-storage-tiers": { src: src("az900-storage-tiers.svg"), ...own },
  "az900-redundancy": { src: src("az900-redundancy.svg"), ...own },
  "az900-defence-in-depth": { src: src("az900-defence-in-depth.svg"), ...own },
  "az900-identity": { src: src("az900-identity.svg"), ...own },
  "az900-cost-factors": { src: src("az900-cost-factors.svg"), ...own },
  "az900-governance": { src: src("az900-governance.svg"), ...own },
  "az900-management-tools": { src: src("az900-management-tools.svg"), ...own },
  "az900-monitoring": { src: src("az900-monitoring.svg"), ...own },
  "az900-exam-path": { src: src("az900-exam-path.svg"), ...own },
};
